const CARSPERPAGE = 7;
const WINNERSPERPAGE = 10;
const ICONWINNERWIDTH = 64;
const ICONWINNERHEIGHT = 34;
const CARSBUNCHNBR = 100;
const HEXCOLORLETTERS = 6;
const INPUTCOLOR = '#ffffff';

export {
  CARSPERPAGE,
  WINNERSPERPAGE,
  ICONWINNERWIDTH,
  ICONWINNERHEIGHT,
  CARSBUNCHNBR,
  INPUTCOLOR,
  HEXCOLORLETTERS,
};
