const CARSPERPAGE = 7;
const WINNERSPERPAGE = 10;
const ICONWINNERWIDTH = 64;
const ICONWINNERHEIGHT = 34;
const CARSBUNCHNBR = 10; // НЕ ЗАБУДЬ ЗАМЕНИТЬ на 100
const HEXCOLORLETTERS = 6;
const INPUTCOLOR = '#ffffff';
const MILICECINCEC = 1000;
const TIMEOUTWINNER = 5000;
const ANIMATIONCOEFF = 3;
const CARFINISHOFFSET = 238;

export {
  CARSPERPAGE,
  WINNERSPERPAGE,
  ICONWINNERWIDTH,
  ICONWINNERHEIGHT,
  CARSBUNCHNBR,
  INPUTCOLOR,
  HEXCOLORLETTERS,
  TIMEOUTWINNER,
  ANIMATIONCOEFF,
  CARFINISHOFFSET,
  MILICECINCEC
};
